#!/bin/bash

if true ; then
	cat <<- EOF > /etc/logrotate.d/freepbx-core-dbug
	/var/log/asterisk/freepbx_dbug{
		size 500M
		missingok
		rotate 7
		notifempty
		sharedscripts
		create 0640 asterisk asterisk
	}
	EOF
fi
